In [2]:
# from dotenv import load_dotenv
import os
# # load_dotenv()

In [3]:
os.environ.get("ALPACA_KEY")

'PKHU5Z6JFZFKRQR5CZBN'

In [28]:
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime, timedelta

# no keys required for data
client = StockHistoricalDataClient(api_key=os.environ.get("ALPACA_KEY"),
                                   secret_key=os.environ.get("ALPACA_SECRET_KEY"))

In [29]:
datetime.now() - timedelta(minutes=15)

datetime.datetime(2025, 7, 2, 16, 31, 12, 577501)

TypeError: TimeFrame.__init__() missing 1 required positional argument: 'unit'

In [33]:

request_params = StockBarsRequest(
                        symbol_or_symbols=["MSFT"],
                        timeframe=TimeFrame.Hour,
                        start=datetime(2000, 7, 1),
                        end=datetime.now() - timedelta(days=1)
                 )

bars = client.get_stock_bars(request_params)

# convert to dataframe
bars = bars.df

In [35]:
bars.head()

                                   open   high    low  close    volume  \
symbol timestamp
MSFT   2016-01-01 00:00:00+00:00  55.58  55.58  55.50  55.55     498.0
       2016-01-04 09:00:00+00:00  55.48  55.48  54.55  54.55    1009.0
       2016-01-04 11:00:00+00:00  54.49  54.49  54.49  54.49     583.0
       2016-01-04 12:00:00+00:00  54.36  54.45  54.21  54.40   11170.0
       2016-01-04 13:00:00+00:00  54.45  54.70  54.21  54.50  107488.0

                                  trade_count       vwap
symbol timestamp
MSFT   2016-01-01 00:00:00+00:00          4.0  55.552500
       2016-01-04 09:00:00+00:00          9.0  54.721918
       2016-01-04 11:00:00+00:00          7.0  54.490000
       2016-01-04 12:00:00+00:00         59.0  54.378302
       2016-01-04 13:00:00+00:00        174.0  54.511455

In [36]:
bars.tail()

                                     open    high      low     close  \
symbol timestamp
MSFT   2025-07-01 12:00:00+00:00  498.230  498.41  496.167  497.8180
       2025-07-01 13:00:00+00:00  497.570  498.05  495.390  497.4650
       2025-07-01 14:00:00+00:00  497.380  498.02  495.270  495.3925
       2025-07-01 15:00:00+00:00  495.372  495.59  491.810  491.8450
       2025-07-01 16:00:00+00:00  491.845  494.05  490.980  493.4900

                                     volume  trade_count        vwap
symbol timestamp
MSFT   2025-07-01 12:00:00+00:00    52605.0       2214.0  497.625751
       2025-07-01 13:00:00+00:00  1892187.0      47052.0  496.926952
       2025-07-01 14:00:00+00:00  2502254.0      70995.0  496.772148
       2025-07-01 15:00:00+00:00  2845662.0      75606.0  493.228143
       2025-07-01 16:00:00+00:00  2079410.0      49808.0  492.308033

In [37]:
bars.shape

(36035, 7)

In [39]:
import pandas as pd

In [42]:
df = pd.read_csv("MSFT_H1_200309101600_202412312200.csv", delimiter='\t')

In [43]:
df.head()

,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<VOL>,<SPREAD>
0,2003.09.10,16:00:00,28.02,28.18,27.90,28.12,11983,9585041,0
1,2003.09.10,17:00:00,28.05,28.13,27.95,28.06,10328,7002848,0
2,2003.09.10,18:00:00,28.06,28.09,27.92,28.02,7076,4792130,0
3,2003.09.10,19:00:00,28.02,28.07,27.96,28.04,5745,3831116,0
4,2003.09.10,20:00:00,28.01,28.09,27.91,27.96,5796,3896840,0

In [44]:
df.tail()

,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<VOL>,<SPREAD>
37525,2024.12.31,18:00:00,424.83,424.87,422.78,423.19,2043,378414,0
37526,2024.12.31,19:00:00,423.17,423.68,421.86,423.68,2413,456141,0
37527,2024.12.31,20:00:00,423.55,423.81,421.71,422.00,2165,385722,0
37528,2024.12.31,21:00:00,421.93,423.00,421.55,422.76,1931,322223,0
37529,2024.12.31,22:00:00,422.62,423.37,420.66,421.30,7540,1117223,0